# Generated by Django 6.0.5 on 2026-05-09 13:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('calories', models.PositiveIntegerField()),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
